### ISSUE TITLE
Several Questions on Three-body Problem

### ISSUE THREAD

**Issue by sdogsq** [juntang-zhuang/torch_ACA#4]
Hi there,
Recently I am trying to re-produce the NODE version results of three-body problem [in your paper](http://proceedings.mlr.press/v119/zhuang20a.html). 
Unfortunately, I notice that only ODE version is uploaded in this repo. Thus I follow the settings in NODE experiments as following.
![image](https://user-images.githubusercontent.com/4051226/114809665-2f30e980-9ddd-11eb-932b-bc2435ada063.png)

I rewrite net module and add augmented input channels.

```python
class TorchThreeBodyEquations(nn.Module): ## 1 layer FC
    def __init__(self):
        super(TorchThreeBodyEquations, self).__init__()
        self.elu = nn.ELU(inplace=False)
        self.fc1 = nn.Linear(45,9)
        self.fc1_ = nn.Linear(9,20)
        self.fc2_ = nn.Linear(20,20)
        self.fc3_ = nn.Linear(20,9)
        self.m1 = nn.Parameter((torch.rand(1) - 0.5)* 0.20 + 1.0)
        self.m2 = nn.Parameter((torch.rand(1) - 0.5)* 0.20 + 1.0)
        self.m3 = nn.Parameter((torch.rand(1) - 0.5)* 0.20 + 1.0)
    def forward(self, t, w):
        r1 = w[...,:3]
        r2 = w[...,3:6]
        r3 = w[...,6:9]
        v1 = w[...,9:12]
        v2 = w[...,12:15]
        v3 = w[...,15:18]
        r12 = torch.norm(r2 - r1, dim = -1)[:,None]
        r13 = torch.norm(r3 - r1, dim = -1)[:,None]
        r23 = torch.norm(r3 - r2, dim = -1)[:,None]
        inn = torch.zeros(w.shape[0],45)
        inn[...,:9] = torch.cat((r1,r2,r3),dim = -1)
        inn[...,9:18] = torch.cat((r1-r2,r1-r3,r2-r3),dim = -1)
        inn[...,18:27] = torch.cat(( (r1-r2)/r12, (r1-r3)/r13, (r2-r3)/r23 ),dim = -1)
        inn[...,27:36] = torch.cat(( (r1-r2)/r12**2, (r1-r3)/r13**2, (r2-r3)/r23**2 ),dim = -1)
        inn[...,36:45] = torch.cat(( (r1-r2)/r12**3, (r1-r3)/r13**3, (r2-r3)/r23**3 ),dim = -1)
        dvbydt = K1 * self.fc1(inn)
        dr1bydt = K2 * v1
        dr2bydt = K2 * v2
        dr3bydt = K2 * v3
        derivs = torch.cat((dr1bydt, dr2bydt,dr3bydt, dvbydt), dim=-1)
        return derivs
```
But I can hardly achieve the Test MSE as described in
![image](https://user-images.githubusercontent.com/4051226/114810754-5092d500-9ddf-11eb-8562-7649840c9cc9.png)

May I ask if there is something wrong in my code? Thank you a lot!

PS:
I notice the lr_decay is 0.99 in the supplementary.
![image](https://user-images.githubusercontent.com/4051226/114810300-6227ad00-9dde-11eb-9cc2-7e6400e62367.png)
However it is 0.95 in [this repo](https://github.com/juntang-zhuang/torch_ACA/blob/dense_state2/three_body_problem.py).
So are atol and rtol parameter.

Look forward to your reply and thank you very much!

**Comment by juntang-zhuang** [comment]
Hi, I think I refer to "two-layer MLP" by saying "one (hidden) layer" as a universal function approximator, , you will need some module like  "Linear1 ( tanh (Linear2 (input)))" with Linear2 sufficiently wide (I forgot the channel number in my experiments).

**Comment by sdogsq** [comment]
Thank you very much!
